<a href="https://colab.research.google.com/github/paras9o9/HobbyFi-Intent-Classifier/blob/main/notebooks/hobbyfi_intent_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.calibration import CalibratedClassifierCV
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

# Label Dataset (160 quires, 8 intents, 20 each)

In [17]:
data = []

read_revenue = [
    "What is today's revenue?", "Show me revenue for this month", "How much did we earn yesterday?",
    "Give me total revenue for badminton this week", "What was our revenue last week?",
    "Show revenue breakdown by sport category", "How much revenue did swimming generate this month?",
    "What is the total revenue this quarter?", "Show revenue for the last 7 days",
    "How much money did we make today from yoga classes?", "Give me revenue comparison for this month vs last month",
    "What is our average daily revenue?", "Show revenue generated from trial conversions",
    "How much revenue came from Jaipur vendors this week?", "Total revenue collected in June",
    "Show revenue trend for the last 30 days", "What was the highest revenue day this month?",
    "Give me revenue split by membership plan", "How much did badminton earn today?",
    "Show total earnings for performing arts category"
]

for q in read_revenue: data.append((q, "read_revenue"))

read_trial_users = [
    "List trial users of badminton", "Show all users on free trial for yoga",
    "Who are the trial users for swimming?", "Give me list of active trials this month",
    "Show trial users who joined this week", "List all free trial signups for dance",
    "How many users are currently on trial for fitness?", "Show trial users expiring today",
    "List new trial users for badminton this week", "Who signed up for a trial in the last 3 days?",
    "Show me all pending trial approvals", "List trial users for martial arts",
    "Give me the count of active trials right now", "Show trial users who haven't converted yet",
    "List trial signups from Jaipur location", "Show trial users for chess coaching",
    "Who are the trial users interested in music classes?", "List all expired trial users this month",
    "Show trial conversion rate for badminton", "Give me trial users sorted by signup date"
]

for q in read_trial_users: data.append((q, "read_trial_users"))

read_membership_status = [
    "Show all members with expired membership", "List users whose membership ends this week",
    "How many active members do we have?", "Show membership status for user Alex",
    "List members whose plan expires today", "Show all premium members",
    "How many members renewed this month?", "List users with paused memberships",
    "Show membership status for user 456", "Give me count of active vs inactive members",
    "List all members joining this month", "Show members with membership expiring in 3 days",
    "How many members do we have in badminton category?", "Show membership history for user Priya",
    "List members eligible for renewal reminders", "Show all members with monthly plan",
    "Give me list of inactive members this quarter", "Show membership status breakdown by plan type",
    "List members who cancelled last month", "Show current member count for yoga"
]

for q in read_membership_status: data.append((q, "read_membership_status"))



read_transactions = [
    "Show transaction history for user 202", "List all payments received today",
    "Show failed transactions this week", "Give me transaction log for user Meera",
    "List all refunds processed this month", "Show payment method breakdown for this week",
    "Give me transactions above 5000 rupees", "Show pending payments for badminton members",
    "List all successful transactions today", "Show transaction summary for this quarter",
    "Give me refund requests pending approval", "Show transaction history for vendor Jaipur Fitness",
    "List all payments made via UPI this week", "Show duplicate transactions if any",
    "Give me total number of transactions today", "Show failed payment retries this week",
    "List transactions above average this month", "Show payment breakdown by plan type",
    "Give me transaction details for user 789", "Show all chargebacks this month"
]

for q in read_transactions: data.append((q, "read_transactions"))

read_vendor_info = [
    "List all vendors in Jaipur", "Show my vendor profile details",
    "What sports categories do we offer?", "Show vendor onboarding date",
    "List all active vendors on the platform", "Give me vendor contact details for badminton academy",
    "Show vendor rating and reviews", "List vendors offering dance classes",
    "Show vendor location and address", "Give me list of vendors added this month",
    "Show vendor category distribution", "List top performing vendors this quarter",
    "Show vendor subscription plan details", "Give me vendor id for yoga studio",
    "List vendors with pending verification", "Show vendor operating hours",
    "Give me vendor profile completeness score", "List vendors offering trial classes",
    "Show vendor total user count", "List vendors sorted by revenue"
]

for q in read_vendor_info: data.append((q, "read_vendor_info"))

write_update_membership = [
    "Update membership end date for user 123 to 30th July", "Extend membership of Priya by 15 days",
    "Change plan type for user 456 to premium", "Update membership start date for user 789",
    "Change membership plan for user Alex to annual", "Update membership for user 321 to monthly plan",
    "Modify membership end date for user Meera", "Change user 202's plan from basic to premium",
    "Update membership renewal date for user Rohan", "Extend membership validity for user 555 by a month",
    "Change membership status to active for user 888", "Update plan type for user 999 to gold",
    "Modify membership dates for user Priya to next quarter", "Change membership category for user 111",
    "Update user 222's membership to include badminton", "Extend membership for user 333 till December",
    "Change membership tier for user 444 to platinum", "Update membership renewal for user 666",
    "Modify plan duration for user 777 to 6 months", "Change membership end date for user 909 to August"
]

for q in write_update_membership: data.append((q, "write_update_membership"))

write_extend_trial = [
    "Increase the free trial of this user by 7 days", "Extend trial for user 789 to 14 days",
    "Give user Rohan 5 more trial days", "Extend trial period for user Meera by 10 days",
    "Add 3 extra trial days for user 456", "Increase trial duration for user Priya to 21 days",
    "Extend free trial for user 321 by a week", "Give user 555 additional 2 trial days",
    "Extend badminton trial for user 202 by 5 days", "Increase trial length for user 888 to 30 days",
    "Add one more week of trial for user 999", "Extend yoga trial for user 111 by 4 days",
    "Increase trial duration for user 222 by 6 days", "Give user 333 extended trial till next week",
    "Extend swimming trial for user 444 by 3 days", "Add 10 extra trial days for user 666",
    "Extend trial for user 777 until end of month", "Increase free trial for user Rohan by 15 days",
    "Extend dance class trial for user Alex by a week", "Give user 909 5 more days of trial access"
]

for q in write_extend_trial: data.append((q, "write_extend_trial"))

write_cancel_subscription = [
    "Cancel subscription for user 321", "Deactivate membership for user Meera",
    "Cancel membership plan for user 456", "Terminate subscription for user Priya",
    "Deactivate user 789's account", "Cancel plan renewal for user Rohan",
    "Stop subscription for user 202", "Deactivate membership immediately for user 555",
    "Cancel badminton membership for user 888", "Terminate plan for user 999 effective today",
    "Deactivate trial and subscription for user 111", "Cancel auto-renewal for user 222",
    "Stop membership plan for user 333", "Deactivate account for user 444 permanently",
    "Cancel subscription request from user 666", "Terminate membership for user 777 this week",
    "Deactivate premium plan for user Alex", "Cancel yoga membership for user 909",
    "Stop subscription renewal for user 990", "Deactivate account access for user 010"
]

for q in write_cancel_subscription: data.append((q, "write_cancel_subscription"))

df = pd.DataFrame(data, columns=["query", "intent"]).drop_duplicates().reset_index(drop=True)
df.to_csv("hobbyfi_sample_queries.csv", index=False)
print(len(df))
df["intent"].value_counts()

160

intent
read_revenue                 20
read_trial_users             20
read_membership_status       20
read_transactions            20
read_vendor_info             20
write_update_membership      20
write_extend_trial           20
write_cancel_subscription    20
Name: count, dtype: int64

# Train/test split + TF-IDF vectorisation

In [18]:
X_train, X_test, y_train, y_test = train_test_split(df["query"], df["intent"], test_size=0.25, random_state=42, stratify=df["intent"])

vectorizer = TfidfVectorizer(ngram_range=(1, 2), min_df=1, sublinear_tf=True)
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# Baseline LinearSVC classifier

In [19]:
clf = LinearSVC(C=1.0)
clf.fit(X_train_vec, y_train)
preds = clf.predict(X_test_vec)

print("Baseline LinearSVC accuracy:", accuracy_score(y_test, preds))
print(classification_report(y_test, preds, zero_division=0))

Baseline LinearSVC accuracy: 0.975
                           precision    recall  f1-score   support

   read_membership_status       0.83      1.00      0.91         5
             read_revenue       1.00      1.00      1.00         5
        read_transactions       1.00      0.80      0.89         5
         read_trial_users       1.00      1.00      1.00         5
         read_vendor_info       1.00      1.00      1.00         5
write_cancel_subscription       1.00      1.00      1.00         5
       write_extend_trial       1.00      1.00      1.00         5
  write_update_membership       1.00      1.00      1.00         5

                 accuracy                           0.97        40
                macro avg       0.98      0.97      0.97        40
             weighted avg       0.98      0.97      0.97        40

# Confidence calibration using CalibratedClassifierCV

In [20]:
base_clf = LinearSVC(C=1.0)
calibrated_clf = CalibratedClassifierCV(base_clf, method="sigmoid", cv=5)
calibrated_clf.fit(X_train_vec, y_train)

preds_cal = calibrated_clf.predict(X_test_vec)
acc_cal = accuracy_score(y_test, preds_cal)

print("Calibrated model accuracy:", acc_cal)
print(classification_report(y_test, preds_cal, zero_division=0))

Calibrated model accuracy: 0.975
                           precision    recall  f1-score   support

   read_membership_status       0.83      1.00      0.91         5
             read_revenue       1.00      1.00      1.00         5
        read_transactions       1.00      0.80      0.89         5
         read_trial_users       1.00      1.00      1.00         5
         read_vendor_info       1.00      1.00      1.00         5
write_cancel_subscription       1.00      1.00      1.00         5
       write_extend_trial       1.00      1.00      1.00         5
  write_update_membership       1.00      1.00      1.00         5

                 accuracy                           0.97        40
                macro avg       0.98      0.97      0.97        40
             weighted avg       0.98      0.97      0.97        40

# Confidence-gated prediction function (guardrail)

In [21]:
def predict_with_calibrated_confidence(query, threshold=0.5):
  vec = vectorizer.transform([query])
  probs = calibrated_clf.predict_proba(vec)[0]
  top_idx = np.argmax(probs)
  confidence = probs[top_idx]
  intent = calibrated_clf.classes_[top_idx]
  if confidence < threshold:
    return "CLARIFY_NEEDED", round(confidence, 3)
  return intent, round(confidence, 3)

# Vendors queries sample test

In [22]:
test_queries = [
    "What is the revenue today?",
    "list trial users of badminton game",
    "update this user membership date",
    "increase the free trial of this user",
    "asdkjaskdj random text",
    "how many members do we have right now?",
    "please cancel this guy's plan",
    "can you show me payments made today?",
]

results_cal = [(q, *predict_with_calibrated_confidence(q)) for q in test_queries]
results_cal_df = pd.DataFrame(results_cal, columns=["query", "predicted_intent", "confidence"])
results_cal_df.to_csv("hobbyfi_intent_prediction_calibrated.csv", index=False)
print(results_cal_df)

                                    query           predicted_intent  \
0              What is the revenue today?               read_revenue
1      list trial users of badminton game           read_trial_users
2        update this user membership date    write_update_membership
3    increase the free trial of this user         write_extend_trial
4                  asdkjaskdj random text             CLARIFY_NEEDED
5  how many members do we have right now?     read_membership_status
6           please cancel this guy's plan  write_cancel_subscription
7    can you show me payments made today?          read_transactions

   confidence
0       0.756
1       0.823
2       0.725
3       0.638
4       0.179
5       0.612
6       0.661
7       0.669

# Confusion matrix + metrics summary

In [23]:
cm = confusion_matrix(y_test, preds_cal, labels=calibrated_clf.classes_)
cm_df = pd.DataFrame(cm, index=calibrated_clf.classes_, columns=calibrated_clf.classes_)
cm_df.to_csv("hobbyfi_confusion_matrix.csv")

test_probs = calibrated_clf.predict_proba(X_test_vec)
max_probs = test_probs.max(axis=1)
avg_confidence_correct = max_probs[preds_cal == y_test.values].mean()
avg_confidence_incorrect = max_probs[preds_cal != y_test.values].mean() if (preds_cal != y_test.values).sum() > 0 else None

metrics_summary = pd.DataFrame({
    "metric": ["train_samples", "test_samples", "total_samples",
               "accuracy", "macro_f1", "avg_confidence_correct_preds",
               "avg_confidence_wrong_preds", "threshold_used"],
    "value": [len(X_train), len(X_test), len(df), round(acc_cal, 3),
              0.97, round(avg_confidence_correct, 3), avg_confidence_incorrect,
              0.5]})
metrics_summary.to_csv("hobbyfi_model_metrics_calibrated.csv", index=False)

# More Data for the Weak Classes

In [24]:
extra_membership = [
"Show membership status for user 111","List all members with active plans",
"How many members expired this week?","Show member details for user 202",
"List members whose plan is about to expire","Show all members with annual plans",
"How many new members joined today?","List paused memberships this month",
"Show membership renewal reminders for this week","Give me count of premium members",
"List all members with pending payments","Show member plan history for user Rohan",
"How many members are active in yoga category?","List members due for renewal tomorrow",
"Show membership plan distribution","Give me list of members joined last week",
"List all suspended memberships","Show member count by plan type",
"How many members have monthly subscriptions?","List members with upcoming expiry"
]

for q in extra_membership: data.append((q, "read_membership_status"))

extra_transactions = [
"Show payment records for user 111","List all UPI transactions today",
"Give me transaction count for this week","Show refund transactions this month",
"List all card payments received today","Show transaction amount for user 456",
"Give me total transaction value this week","List failed UPI payments today",
"Show payment gateway errors this week","Give me transaction breakdown by payment method",
"List transactions above 1000 rupees today","Show total transaction count this quarter",
"Give me payment receipts for user 789","List all net banking transactions",
"Show transaction status for order 555","Give me payment confirmation for user Priya",
"List all wallet payments this week","Show transaction ID for user 202's payment",
"Give me daily transaction volume","List transactions pending settlement"
]

for q in extra_transactions: data.append((q, "read_transactions"))

df2 = pd.DataFrame(data, columns=["query", "intent"]).drop_duplicates().reset_index(drop=True)
print(len(df2))
df2["intent"].value_counts()

200

intent
read_transactions            40
read_membership_status       40
read_trial_users             20
read_revenue                 20
read_vendor_info             20
write_update_membership      20
write_extend_trial           20
write_cancel_subscription    20
Name: count, dtype: int64

# Evaluating the feature combination and classifier

In [25]:
from sklearn.pipeline import FeatureUnion
from sklearn.base import BaseEstimator, TransformerMixin

df2.to_csv("hobbyfi_sample_queries_v2.csv", index=False)

X_train2, X_test2, y_train2, y_test2 = train_test_split(
    df2["query"], df2["intent"], test_size=0.25, random_state=42, stratify=df2["intent"]
)

word_vec = TfidfVectorizer(ngram_range=(1, 2), min_df=1, sublinear_tf=True)
char_vec = TfidfVectorizer(analyzer="char_wb", ngram_range=(3, 5), min_df=1, sublinear_tf=True)

combined_vec = FeatureUnion([
    ("word", word_vec), ("char", char_vec)
])
X_train2_vec = combined_vec.fit_transform(X_train2)
X_test2_vec = combined_vec.transform(X_test2)

base_clf2 = LinearSVC(C=1.0)
calibrated_clf2 = CalibratedClassifierCV(base_clf2, method="sigmoid", cv=5)
calibrated_clf2.fit(X_train2_vec, y_train2)

preds2 = calibrated_clf2.predict(X_test2_vec)
acc2 = accuracy_score(y_test2, preds2)
report2 = classification_report(y_test2, preds2, zero_division=0)

print(acc2)
print(report2)

0.94
                           precision    recall  f1-score   support

   read_membership_status       1.00      1.00      1.00        10
             read_revenue       0.80      0.80      0.80         5
        read_transactions       0.91      1.00      0.95        10
         read_trial_users       1.00      1.00      1.00         5
         read_vendor_info       1.00      0.80      0.89         5
write_cancel_subscription       1.00      0.80      0.89         5
       write_extend_trial       1.00      1.00      1.00         5
  write_update_membership       0.83      1.00      0.91         5

                 accuracy                           0.94        50
                macro avg       0.94      0.93      0.93        50
             weighted avg       0.95      0.94      0.94        50

# Testing the word-only model and intent prediction

In [26]:
word_only_vec = TfidfVectorizer(ngram_range=(1, 2), min_df=1, sublinear_tf=True)
X_train2_w = word_only_vec.fit_transform(X_train2)
X_test2_w = word_only_vec.transform(X_test2)

base_clf3 = LinearSVC(C=1.0)
calibrated_clf3 = CalibratedClassifierCV(base_clf2, method="sigmoid", cv=5)
calibrated_clf3.fit(X_train2_w, y_train2)
preds3 = calibrated_clf3.predict(X_test2_w)
acc3 = accuracy_score(y_test2, preds3)
print("word-only on expanded data:", acc3)
print(classification_report(y_test2, preds3, zero_division=0))

def predict_v2(query, threshold=0.4, vec=word_only_vec, model=calibrated_clf3):
  v = vec.transform([query])
  probs = model.predict_proba(v)[0]
  top_idx = np.argmax(probs)
  conf = probs[top_idx]
  intent = model.classes_[top_idx]
  return ("CLARIFY_NEEDED", round(conf, 3)) if conf < threshold else (intent, round(conf, 3))

test_queries = [
    "What is the revenue today?","list trial users of badminton game",
    "update this user membership date","increase the free trial of this user",
    "asdkjaskdj random text","how many members do we have right now",
    "please cancel this guy's plan","can you show me payments made today",
]
for q in test_queries:
    print(q, "->", predict_v2(q))

word-only on expanded data: 0.92
                           precision    recall  f1-score   support

   read_membership_status       1.00      1.00      1.00        10
             read_revenue       0.80      0.80      0.80         5
        read_transactions       0.91      1.00      0.95        10
         read_trial_users       0.83      1.00      0.91         5
         read_vendor_info       1.00      0.60      0.75         5
write_cancel_subscription       1.00      0.80      0.89         5
       write_extend_trial       1.00      1.00      1.00         5
  write_update_membership       0.83      1.00      0.91         5

                 accuracy                           0.92        50
                macro avg       0.92      0.90      0.90        50
             weighted avg       0.93      0.92      0.92        50

What is the revenue today? -> ('read_revenue', np.float64(0.845))
list trial users of badminton game -> ('read_trial_users', np.float64(0.837))
update this user membership date -> ('write_update_membership', np.float64(0.77))
increase the free trial of this user -> ('write_extend_trial', np.float64(0.67))
asdkjaskdj random text -> ('CLARIFY_NEEDED', np.float64(0.216))
how many members do we have right now -> ('read_membership_status', np.float64(0.745))
please cancel this guy's plan -> ('write_cancel_subscription', np.float64(0.711))
can you show me payments made today -> ('read_transactions', np.float64(0.692))